/*!
 * fractional.js - v1.0.0 - (https://github.com/lucasgruwez/fractional.js)
 * Copyright 2017 Lucas Gruwez.
 * Licensed under MIT
 * https://github.com/lucasgruwez/fractional.js
 */

(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
window.Fractional = require('./fractional.min.js')

},{"./fractional.min.js":2}],2:[function(require,module,exports){
"use strict";var _typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(n){return typeof n}:function(n){return n&&"function"==typeof Symbol&&n.constructor===Symbol&&n!==Symbol.prototype?"symbol":typeof n},_createClass=function(){function r(n,t){for(var e=0;e<t.length;e++){var r=t[e];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(n,r.key,r)}}return function(n,t,e){return t&&r(n.prototype,t),e&&r(n,e),n}}();function _classCallCheck(n,t){if(!(n instanceof t))throw new TypeError("Cannot call a class as a function")}var err={divideBy0:new EvalError("Can't divide by 0"),invalidParam:new TypeError("Invaild paramteter")},F=function(n){return n instanceof Fraction?n:("number"==typeof n&&n%1==0&&(n=[n,1]),new Fraction(n))},Fraction=function(){function a(n,t){if(_classCallCheck(this,a),0==t)throw err.divideBy0;if(n%1==0&&t%1==0)return this.n=Math.abs(n/this._gcd(n,t)),this.d=Math.abs(t/this._gcd(n,t)),n*t<0&&(this.n=-this.n),this;switch(void 0===n?"undefined":_typeof(n)){case"object":if("n"in n&&"d"in n)return new a(n.n,n.d);if(0 in n)return new a(n[0],n[1]);throw err.invalidParam;case"number":if(n%1==0)return new a(n,1);for(var e=1e8,r=[0,1],i=[Math.ceil(n),1];r[1]<=e&&i[1]<=e;){var o=(r[0]+i[0])/(r[1]+i[1]);if(n===o)return r[1]+i[1]<=e?new a(r[0]+i[0],r[1]+i[1]):r[1]>i[1]?new a(i):new a(r);o<n?r=[r[0]+i[0],r[1]+i[1]]:i=[r[0]+i[0],r[1]+i[1]]}return r[1]>e?new a(i):new a(r);default:throw err.invalidParam}}return _createClass(a,[{key:"toString",value:function(){return this.n+"/"+this.d}},{key:"valueOf",value:function(){return this.n/this.d}},{key:"add",value:function(n){return n=F(n),new a(this.n*n.d+this.d*n.n,this.d*n.d)}},{key:"sub",value:function(n){return n=F(n),new a(this.n*n.d-this.d*n.n,this.d*n.d)}},{key:"mul",value:function(n){return n=F(n),new a(this.n*n.n,this.d*n.d)}},{key:"div",value:function(n){return n=F(n),new a(this.n*n.d,this.d*n.n)}},{key:"reciprocal",value:function(){return new a(1,1).div(this)}},{key:"pow",value:function(n){return(n=F(n).valueOf())%1==0&&0<=n?new a(Math.pow(this.n,n),Math.pow(this.d,n)):n%1==0&&n<=0?new a(Math.pow(this.d,-n),Math.pow(this.n,-n)):new a(Math.pow(this.n,n)/Math.pow(this.d,n))}},{key:"nthRoot",value:function(n){return this.pow(new a(1,n))}},{key:"_gcd",value:function(n,t){for(;t;){var e=n%t;n=t,t=e}return n}}]),a}();module.exports=Fraction;
},{}]},{},[1]);
